### ISSUE TITLE
Having some noob qeustions

### ISSUE THREAD

**Issue by seyo-IV** [EdBuilds/rpi_bonnet_dashboard#3]
I had to run `sudo apt install python-backports.functools-lru-cache` in order to be able to run `pipenv install`. Else I got this Error: `ImportError: No module named functools_lru_cache`

**Comment by seyo-IV** [comment]
Ok I just tested it and i get this:
```
Traceback (most recent call last):
  File "dashboard.py", line 1, in <module>
    import board
ModuleNotFoundError: No module named 'board'
```
Doesn't seem to find the needed module on the internet :/. Can you help out a noob?

**Comment by seyo-IV** [comment]
Ok i rerun pipenv install now im getting another error:
```
Traceback (most recent call last):
  File "dashboard.py", line 116, in <module>
    i2c = busio.I2C(board.SCL, board.SDA)
  File "/root/.local/share/virtualenvs/rpi_bonnet_dashboard-3oLTB1UF/lib/python3.7/site-packages/busio.py", line 19, in __init__
    self.init(scl, sda, frequency)
  File "/root/.local/share/virtualenvs/rpi_bonnet_dashboard-3oLTB1UF/lib/python3.7/site-packages/busio.py", line 49, in init
    "No Hardware I2C on (scl,sda)={}\nValid I2C ports: {}".format((scl, sda), i2cPorts)
ValueError: No Hardware I2C on (scl,sda)=(3, 2)
Valid I2C ports: ((3, 3, 2), (1, 3, 2), (0, 1, 0))
```
Im assuming the OLED display is not recognized for some reason. But im still not sure.

**Comment by seyo-IV** [comment]
okay had to enable some stuff first.
Like described here: https://learn.adafruit.com/adafruits-raspberry-pi-lesson-4-gpio-setup/configuring-i2c
